#!/usr/bin/env node
// Generated by facility — https://github.com/theam/facility
//
// Weekly synthetic canary. Flies the REAL pipeline: posts the canonical
// /architect probe on the pinned canary issue, then asserts the crew run
// appears, succeeds, and replies. Any broken link turns this workflow red,
// and the health monitor (which watches facility-canary) raises it in the
// incident issue the next morning.
//
// Authorization is by MESSAGE, not by sender: the crew workflow admits the
// canary bot only for a comment that is byte-identical (SHA-256, CR-stripped)
// to CANARY_PROBE_BODY below, on an agent-canary-labeled issue, resolving to
// /architect. A leaked App key can therefore at worst replay this fixed
// read-only probe — never run attacker-chosen instructions. The pinned hash
// in facility-crew.yml is kept in sync by the watchtower-locked guard.
//
// The probe must be posted with a GitHub App or PAT token (CANARY_COMMENT_TOKEN):
// comments posted with the workflow's own GITHUB_TOKEN trigger no workflows
// at all (GitHub's recursion guard) — the canary would test nothing.
// Env: GH_TOKEN, GITHUB_REPOSITORY, CANARY_COMMENT_TOKEN (App/PAT).
import { execFileSync } from "node:child_process";

export const CANARY_PROBE_BODY = [
  "/architect",
  "",
  "Facility canary probe. This is a scheduled synthetic check of the agent",
  "pipeline, authorized by message hash. Reply with a one-paragraph health",
  "summary of this repository's facility setup (crew workflows present,",
  "STANDARD.md readable, guards runnable) and stop. Do not plan features, do",
  "not read beyond what the summary needs, and do not modify anything.",
].join("\n");

const CREW_WORKFLOW = "facility-crew";
const POLL_SECONDS = 30;
const TIMEOUT_MINUTES = 45;

async function main() {
  const repo = process.env.GITHUB_REPOSITORY;
  if (!repo) throw new Error("GITHUB_REPOSITORY is required");
  const token = process.env.CANARY_COMMENT_TOKEN;
  if (!token) {
    console.log(
      "::notice::CANARY_COMMENT_TOKEN not configured — canary skipped. Mint it from a GitHub App so the probe comment triggers workflows.",
    );
    return;
  }

  const gh = (args) => execFileSync("gh", args, { encoding: "utf8", maxBuffer: 16 * 1024 * 1024 });
  const api = async (path, init = {}) => {
    const response = await fetch(`https://api.github.com/repos/${repo}/${path}`, {
      ...init,
      headers: {
        authorization: `Bearer ${token}`,
        accept: "application/vnd.github+json",
        ...(init.headers ?? {}),
      },
    });
    if (!response.ok) throw new Error(`${path} → ${response.status}: ${await response.text()}`);
    return response.json();
  };

  // 1. Find (or create) the pinned canary fixture issue.
  try {
    gh([
      "label",
      "create",
      "agent-canary",
      "--force",
      "--color",
      "FFD923",
      "--description",
      "facility canary fixture",
    ]);
  } catch {}
  const issues = JSON.parse(
    gh([
      "issue",
      "list",
      "--label",
      "agent-canary",
      "--state",
      "open",
      "--json",
      "number",
      "--limit",
      "1",
    ]),
  );
  let issueNumber = issues[0]?.number;
  if (!issueNumber) {
    const createdUrl = gh([
      "issue",
      "create",
      "--title",
      "Facility canary",
      "--label",
      "agent-canary",
      "--body",
      "Pinned fixture issue for the weekly synthetic canary. The probe comments below are posted by the canary workflow; do not comment agent commands here yourself.",
    ]).trim();
    issueNumber = Number(createdUrl.split("/").pop());
    if (!issueNumber) throw new Error(`could not parse issue number from: ${createdUrl}`);
  }

  // 2. Post the canonical probe with the App token (so it triggers workflows).
  const startedAt = new Date().toISOString();
  await api(`issues/${issueNumber}/comments`, {
    method: "POST",
    body: JSON.stringify({ body: CANARY_PROBE_BODY }),
  });
  console.log(`probe posted on #${issueNumber} at ${startedAt}`);

  // 3. Assert the crew run appears and succeeds.
  const deadline = Date.now() + TIMEOUT_MINUTES * 60_000;
  let run = null;
  while (Date.now() < deadline) {
    const { workflow_runs: runs } = JSON.parse(
      gh([
        "api",
        `repos/${repo}/actions/runs?event=issue_comment&created=>${startedAt}&per_page=20`,
      ]),
    );
    run = runs.find((r) => r.name === CREW_WORKFLOW) ?? null;
    if (run && run.status === "completed") break;
    await new Promise((resolve) => setTimeout(resolve, POLL_SECONDS * 1000));
  }
  if (!run)
    throw new Error(
      `no ${CREW_WORKFLOW} run appeared within ${TIMEOUT_MINUTES} minutes — the trigger chain is broken`,
    );
  if (run.conclusion !== "success")
    throw new Error(`crew run concluded '${run.conclusion}': ${run.html_url}`);

  // 4. Assert a reply landed on the issue after the probe.
  const comments = JSON.parse(
    gh(["api", `repos/${repo}/issues/${issueNumber}/comments?per_page=100`]),
  );
  const reply = comments.find((c) => c.created_at > startedAt && c.body !== CANARY_PROBE_BODY);
  if (!reply)
    throw new Error(
      `crew run succeeded but no reply landed on #${issueNumber} — the reply chain is broken`,
    );

  console.log(`canary green: run ${run.html_url} · reply ${reply.html_url}`);
}

// Import-safe: the watchtower-locked guard imports CANARY_PROBE_BODY without running the probe.
if (process.argv[1] && import.meta.url.endsWith(process.argv[1].split("/").pop())) {
  main().catch((error) => {
    console.error(`::error::${error.message}`);
    process.exit(1);
  });
}
