#!/usr/bin/env node
// Generated by facility — https://github.com/theam/facility
//
// Daily health monitor. Watches the watchmen: pulls the last 24h of facility
// workflow runs straight from the GitHub API (deliberately NOT from any
// telemetry pipeline the facility itself writes — the monitor must not
// depend on what it monitors), checks failure streaks and run budgets, and
// maintains a single incident issue. The monitor run itself goes RED when
// the facility is unhealthy, so the Actions tab is the at-a-glance signal.
//
// This workflow is intentionally NOT in its own watchlist (no self-recursion).
// Budgets live next to this file in budgets.json — a reviewed file, not a
// dashboard setting.
// Env: GH_TOKEN (rw issues), GITHUB_REPOSITORY.
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const repo = process.env.GITHUB_REPOSITORY;
if (!repo) throw new Error("GITHUB_REPOSITORY is required");
const here = dirname(fileURLToPath(import.meta.url));

const WATCHLIST = [
  "facility-crew",
  "facility-review",
  "facility-address-review",
  "facility-doctor",
  "facility-security-sweep",
  "facility-canary",
];

let budgets = { maxDailyFailures: { "*": 3 }, maxWeeklyRuns: {} };
try {
  budgets = { ...budgets, ...JSON.parse(readFileSync(join(here, "budgets.json"), "utf8")) };
} catch {}
const budgetFor = (map, name, fallback) => map?.[name] ?? map?.["*"] ?? fallback;

const gh = (args) => execFileSync("gh", args, { encoding: "utf8", maxBuffer: 32 * 1024 * 1024 });
const iso = (hoursAgo) => new Date(Date.now() - hoursAgo * 3600_000).toISOString();
const runsSince = (sinceIso) =>
  JSON.parse(
    gh(["api", `repos/${repo}/actions/runs?created=>${sinceIso}&per_page=100`]),
  ).workflow_runs.filter((r) => WATCHLIST.includes(r.name));

const day = runsSince(iso(24));
const week = runsSince(iso(24 * 7));

const problems = [];
const rows = [];
for (const name of WATCHLIST) {
  const daily = day.filter((r) => r.name === name);
  const failures = daily.filter((r) =>
    ["failure", "startup_failure", "timed_out"].includes(r.conclusion ?? ""),
  );
  const weeklyCount = week.filter((r) => r.name === name).length;
  const maxFail = budgetFor(budgets.maxDailyFailures, name, 3);
  const maxWeekly = budgetFor(budgets.maxWeeklyRuns, name, Infinity);
  if (failures.length >= maxFail) {
    problems.push(
      `**${name}**: ${failures.length} failures in 24h (budget ${maxFail}) — latest: ${failures[0].html_url}`,
    );
  }
  if (weeklyCount > maxWeekly) {
    problems.push(
      `**${name}**: ${weeklyCount} runs this week (budget ${maxWeekly}) — runaway trigger or runaway spend?`,
    );
  }
  if (daily.length || weeklyCount) {
    rows.push(`| ${name} | ${daily.length} | ${failures.length} | ${weeklyCount} |`);
  }
}

const MARKER = "facility-health";
try {
  gh([
    "label",
    "create",
    MARKER,
    "--force",
    "--color",
    "D1242F",
    "--description",
    "facility health incident",
  ]);
} catch {}
const openIncidents = JSON.parse(
  gh(["issue", "list", "--label", MARKER, "--state", "open", "--json", "number", "--limit", "1"]),
);

const report = [
  `Health check ${new Date().toISOString()} — last 24h / 7d, from the GitHub API.`,
  "",
  "| workflow | runs 24h | failures 24h | runs 7d |",
  "|---|---|---|---|",
  ...rows,
  "",
  problems.length
    ? `### Problems\n${problems.map((p) => `- ${p}`).join("\n")}`
    : "All watched workflows within budget.",
].join("\n");

if (problems.length) {
  if (openIncidents.length === 0) {
    gh([
      "issue",
      "create",
      "--title",
      "Facility health incident",
      "--label",
      MARKER,
      "--body",
      report,
    ]);
  } else {
    gh(["issue", "comment", String(openIncidents[0].number), "--body", report]);
  }
  console.error(report);
  process.exit(1); // red run = the at-a-glance signal
}

if (openIncidents.length > 0) {
  gh(["issue", "comment", String(openIncidents[0].number), "--body", `Recovered.\n\n${report}`]);
  gh(["issue", "close", String(openIncidents[0].number)]);
}
console.log(report);
