/** Every versioned control-plane route exposed by Facility 0.12. */
export const FACILITY_V1_ROUTES = [
  "DELETE /v1/keys/:keyId",
  "DELETE /v1/members/:userId",
  "DELETE /v1/projects/:projectId",
  "DELETE /v1/projects/:projectId/repos/:repoId",
  "DELETE /v1/projects/:projectId/workspace-stories/:storyId/workspace",
  "DELETE /v1/roles/:roleId",
  "GET /v1/github/installations",
  "GET /v1/github/installations/:installationId/repos",
  "GET /v1/keys",
  "GET /v1/me",
  "GET /v1/members",
  "GET /v1/org",
  "GET /v1/projects",
  "GET /v1/projects/:projectId",
  "GET /v1/projects/:projectId/audit",
  "GET /v1/projects/:projectId/budget",
  "GET /v1/projects/:projectId/costs",
  "GET /v1/projects/:projectId/kickstart/preview",
  "GET /v1/projects/:projectId/observability",
  "GET /v1/projects/:projectId/pipeline",
  "GET /v1/projects/:projectId/repos",
  "GET /v1/projects/:projectId/story-agents",
  "GET /v1/projects/:projectId/story-agents/:agentName",
  "GET /v1/projects/:projectId/workspace-stories",
  "GET /v1/projects/:projectId/workspace-stories/:storyId",
  "GET /v1/projects/:projectId/workspace-stories/:storyId/conversation",
  "GET /v1/projects/:projectId/workspace-stories/:storyId/environment",
  "GET /v1/roles",
  "PATCH /v1/members/:userId",
  "PATCH /v1/org",
  "PATCH /v1/projects/:projectId",
  "PATCH /v1/projects/:projectId/budget",
  "PATCH /v1/projects/:projectId/story-agents/:agentName",
  "PATCH /v1/roles/:roleId",
  "POST /v1/keys",
  "POST /v1/members",
  "POST /v1/projects",
  "POST /v1/projects/:projectId/github/sync",
  "POST /v1/projects/:projectId/kickstart",
  "POST /v1/projects/:projectId/repos",
  "POST /v1/projects/:projectId/workspace-stories",
  "POST /v1/projects/:projectId/workspace-stories/:storyId/archive",
  "POST /v1/projects/:projectId/workspace-stories/:storyId/attention/:attentionId/dismiss",
  "POST /v1/projects/:projectId/workspace-stories/:storyId/attention/:attentionId/retry",
  "POST /v1/projects/:projectId/workspace-stories/:storyId/environment/browser-test",
  "POST /v1/projects/:projectId/workspace-stories/:storyId/environment/clean-setup",
  "POST /v1/projects/:projectId/workspace-stories/:storyId/messages",
  "POST /v1/projects/:projectId/workspace-stories/:storyId/preview/:service/open",
  "POST /v1/projects/:projectId/workspace-stories/:storyId/restore",
  "POST /v1/projects/:projectId/workspace-stories/:storyId/suspend",
  "POST /v1/projects/:projectId/workspace-stories/:storyId/turns/:turnId/cancel",
  "POST /v1/roles",
] as const;

export type FacilityV1Route = (typeof FACILITY_V1_ROUTES)[number];
