#!/usr/bin/env node
// Generated by facility — make every successful automated review observable.
import { execFileSync } from "node:child_process";

const repo = required("GITHUB_REPOSITORY");
const prNumber = required("FACILITY_PR_NUMBER");
const startedAt = required("FACILITY_REVIEW_STARTED_AT");
const inlineComments = ghJson([
  "api",
  `repos/${repo}/pulls/${prNumber}/comments?per_page=100`,
]).filter((comment) => comment.created_at >= startedAt && comment.user?.type === "Bot");

if (inlineComments.length > 0) {
  console.log(`Facility review produced ${inlineComments.length} inline finding(s).`);
  process.exit(0);
}

const marker = `<!-- facility-review:${process.env.GITHUB_RUN_ID ?? "unknown"} -->`;
const body = [
  "Facility automated review completed with no actionable findings.",
  "",
  "This is advisory evidence, not approval; the required human review and merge gate remain in force.",
  "",
  marker,
].join("\n");
execFileSync("gh", ["api", `repos/${repo}/issues/${prNumber}/comments`, "-f", `body=${body}`], {
  stdio: "inherit",
});

function ghJson(args) {
  return JSON.parse(execFileSync("gh", args, { encoding: "utf8" }));
}

function required(name) {
  const value = process.env[name];
  if (!value) throw new Error(`${name} is required`);
  return value;
}
