// Generated by facility — https://github.com/theam/facility
//
// Small helpers for writing guards. Zero dependencies; everything is yours
// to read and change.
import { execFileSync } from "node:child_process";
import { readdirSync, readFileSync, statSync } from "node:fs";
import { join } from "node:path";

/** Recursively list files under `dir` matching any of `extensions`. */
export function listFiles(dir, extensions, ignore = ["node_modules", ".git"]) {
  const out = [];
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return out;
  }
  for (const entry of entries) {
    if (ignore.includes(entry)) continue;
    const path = join(dir, entry);
    const stats = statSync(path);
    if (stats.isDirectory()) out.push(...listFiles(path, extensions, ignore));
    else if (extensions.some((ext) => entry.endsWith(ext))) out.push(path);
  }
  return out;
}

/** Read a file as UTF-8, returning "" when it does not exist. */
export function readText(path) {
  try {
    return readFileSync(path, "utf8");
  } catch {
    return "";
  }
}

/**
 * Wrap an existing CLI/DB check as a guard instead of re-implementing its
 * logic. The command's non-zero exit becomes a single violation carrying its
 * output tail.
 */
export function commandGuard({ name, description, command, args = [], requires = [] }) {
  return {
    name,
    description,
    requires,
    run() {
      try {
        execFileSync(command, args, { stdio: ["ignore", "pipe", "pipe"], encoding: "utf8" });
        return [];
      } catch (error) {
        const tail = `${error.stdout ?? ""}${error.stderr ?? ""}`
          .trim()
          .split("\n")
          .slice(-12)
          .join("\n");
        return [{ message: `\`${[command, ...args].join(" ")}\` failed:\n${tail}` }];
      }
    },
  };
}

/**
 * Filter violations through a keyed allowlist. Every allowlist entry must
 * carry a written reason; entries that no longer match anything are reported
 * as stale so the list cannot rot.
 */
export function applyAllowlist(violations, allowlist) {
  const used = new Set();
  const kept = violations.filter((violation) => {
    const hit = Object.keys(allowlist).find((key) => violation.key === key);
    if (hit) used.add(hit);
    return !hit;
  });
  for (const key of Object.keys(allowlist)) {
    if (!used.has(key)) {
      kept.push({ message: `stale allowlist entry "${key}" (${allowlist[key]}) — remove it` });
    }
  }
  return kept;
}
