// Generated by facility — https://github.com/theam/facility
//
// Every third-party GitHub Action must be pinned to a full commit SHA.
// Tags and branches are mutable: a compromised action repo can re-point
// `v4` at malicious code and your CI — which holds secrets and write
// tokens — runs it on the next push. A 40-hex SHA cannot be re-pointed.
import { applyAllowlist, listFiles, readText } from "./_kit.mjs";

// key: "<file>:<uses-ref>", value: written reason. Keep this empty unless a
// pin is truly impossible; document why.
const ALLOWLIST = {};

export default {
  name: "actions-pinned",
  description: "third-party GitHub Actions are pinned to full commit SHAs",
  run() {
    const violations = [];
    for (const file of listFiles(".github/workflows", [".yml", ".yaml"])) {
      const lines = readText(file).split("\n");
      lines.forEach((line, index) => {
        const match = line.match(/^\s*(?:-\s+)?uses:\s*([^\s#]+)/);
        if (!match) return;
        const ref = match[1].replace(/^["']|["']$/g, "");
        if (ref.startsWith("./") || ref.startsWith("docker://")) return;
        const pinned = /@[0-9a-f]{40}$/.test(ref);
        if (!pinned) {
          violations.push({
            file,
            line: index + 1,
            key: `${file}:${ref}`,
            message: `"${ref}" is not pinned to a full commit SHA (use @<40-hex-sha> with a version comment)`,
          });
        }
      });
    }
    return applyAllowlist(violations, ALLOWLIST);
  },
};
