// Generated by facility — https://github.com/theam/facility
//
// The watchtower must not quietly rot: a disabled schedule or a drifted
// canary hash turns "the SDLC watches itself" into a false sense of safety.
// This guard locks the design in place: the watchtower and canary stay
// scheduled, and the canary hash pinned in facility-crew.yml matches the
// canonical probe body in .github/facility/watchtower/canary.mjs.
import { createHash } from "node:crypto";
import { pathToFileURL } from "node:url";
import { readText } from "./_kit.mjs";

export default {
  name: "watchtower-locked",
  description: "watchtower/canary stay scheduled and the canary hash stays in sync",
  async run() {
    const violations = [];

    const scheduled = [
      [".github/workflows/facility-watchtower.yml", 2],
      [".github/workflows/facility-canary.yml", 1],
      [".github/workflows/facility-security-sweep.yml", 1],
    ];
    for (const [file, minCrons] of scheduled) {
      const text = readText(file);
      if (!text) {
        violations.push({ file, message: "missing — the facility no longer watches itself" });
        continue;
      }
      const crons = (text.match(/- cron:/g) ?? []).length;
      if (crons < minCrons) {
        violations.push({
          file,
          message: `expected at least ${minCrons} cron schedule(s), found ${crons}`,
        });
      }
    }

    const crew = readText(".github/workflows/facility-crew.yml");
    if (!crew) {
      violations.push({ file: ".github/workflows/facility-crew.yml", message: "missing" });
      return violations;
    }
    try {
      const { CANARY_PROBE_BODY } = await import(
        pathToFileURL(".github/facility/watchtower/canary.mjs").href
      );
      const expected = createHash("sha256")
        .update(CANARY_PROBE_BODY.replace(/\r/g, ""), "utf8")
        .digest("hex");
      if (!crew.includes(expected)) {
        violations.push({
          file: ".github/workflows/facility-crew.yml",
          message: `canary hash out of sync — expected sha256 ${expected} (from canary.mjs CANARY_PROBE_BODY)`,
        });
      }
    } catch {
      violations.push({
        file: ".github/facility/watchtower/canary.mjs",
        message: "missing or unreadable — cannot verify the pinned canary hash",
      });
    }

    return violations;
  },
};
