#!/usr/bin/env node
// Generated by facility — https://github.com/theam/facility
//
// Deterministic, fast invariant checks that run as ONE umbrella status
// instead of a sprawl of bespoke CI steps. Standard toolchain checks
// (typecheck, lint, tests, build) stay as their own statuses — guards are
// only for repo-specific invariants.
//
//   node guards/run.mjs                 run all guards
//   node guards/run.mjs --only=<name>   run one guard (repeatable)
//   node guards/run.mjs --json          machine-readable (CI / agents)
//   node guards/run.mjs --list          list registered guards
//
// A guard is a file in this directory exporting:
//
//   export default {
//     name: "my-invariant",
//     description: "what it enforces, in one line",
//     requires: ["SOME_ENV_VAR"],          // optional: skip (not fail) when absent
//     async run() { return [/* violations */]; },
//   }
//
// A violation: { file?, line?, message }. Empty array = pass.
// Keep guards deterministic and read-only. Justified exceptions belong in an
// in-code ALLOWLIST inside the guard, keyed, with a written reason per entry.
//
// Design goal: adding a new safety invariant is a single small file — easy
// for engineers and for agents to extend. If a rule in STANDARD.md is
// repeatedly missed, it belongs here.
import { readdirSync } from "node:fs";
import { basename, dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const args = process.argv.slice(2);
const asJson = args.includes("--json");
const list = args.includes("--list");
const only = args.filter((a) => a.startsWith("--only=")).map((a) => a.slice(7));

const guardFiles = readdirSync(here)
  .filter(
    (f) =>
      f.endsWith(".mjs") && !f.startsWith("_") && f !== basename(fileURLToPath(import.meta.url)),
  )
  .sort();

const guards = [];
for (const file of guardFiles) {
  const mod = await import(pathToFileURL(join(here, file)).href);
  const guard = mod.default;
  if (!guard?.name || typeof guard.run !== "function") {
    console.error(`guards/${file} does not export a valid guard ({ name, description, run }).`);
    process.exit(1);
  }
  guards.push({ ...guard, file });
}

if (list) {
  for (const g of guards) console.log(`${g.name.padEnd(32)} ${g.description ?? ""}`);
  process.exit(0);
}

const selected = only.length ? guards.filter((g) => only.includes(g.name)) : guards;
if (only.length && selected.length !== only.length) {
  const known = new Set(guards.map((g) => g.name));
  for (const name of only.filter((n) => !known.has(n))) console.error(`Unknown guard: ${name}`);
  process.exit(1);
}

const results = [];
for (const guard of selected) {
  const missing = (guard.requires ?? []).filter((envVar) => !process.env[envVar]);
  if (missing.length) {
    results.push({
      name: guard.name,
      status: "skipped",
      reason: `missing env: ${missing.join(", ")}`,
      violations: [],
    });
    continue;
  }
  try {
    const violations = (await guard.run()) ?? [];
    results.push({ name: guard.name, status: violations.length ? "fail" : "pass", violations });
  } catch (error) {
    results.push({
      name: guard.name,
      status: "fail",
      violations: [{ message: `guard crashed: ${error?.message ?? error}` }],
    });
  }
}

const failed = results.filter((r) => r.status === "fail");

if (asJson) {
  console.log(JSON.stringify({ ok: failed.length === 0, results }, null, 2));
} else {
  for (const r of results) {
    const mark = r.status === "pass" ? "✓" : r.status === "skipped" ? "—" : "✗";
    console.log(`${mark} ${r.name}${r.status === "skipped" ? `  (skipped: ${r.reason})` : ""}`);
    for (const v of r.violations) {
      const where = v.file ? `  ${v.file}${v.line ? `:${v.line}` : ""}  ` : "  ";
      console.log(`  ${where}${v.message}`);
    }
  }
  const ran = results.filter((r) => r.status !== "skipped").length;
  console.log(`\n${ran} guard${ran === 1 ? "" : "s"} ran, ${failed.length} failed.`);
}

process.exit(failed.length ? 1 : 0);
