#!/usr/bin/env node
import { execFileSync } from "node:child_process";
// Generated by facility — https://github.com/theam/facility
//
// Deterministic doctor resolver. Runs on every completed watched workflow and
// decides — with rules, not judgment — what the doctor may do:
//
//   none    not a failure / not a PR / already handled (fingerprint dedup)
//   triage  post one concise comment pointing a human at the failure
//   repair  start the bounded repair agent (crew-authored PRs only, and only
//           when neither the failure nor the PR touches a sensitive surface)
//
// The repair policy is deliberately conservative: human branches get triage,
// never uninvited commits. Sensitive surfaces are always triage-only.
// Env: GH_TOKEN, GITHUB_REPOSITORY, GITHUB_EVENT_PATH, GITHUB_OUTPUT.
import { createHash } from "node:crypto";
import { appendFileSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";

const SENSITIVE_PATHS = [
  ".github/workflows/",
  ".github/facility/",
  "guards/",
  ".claude/",
  ".env",
  "migrations/",
  "supabase/migrations/",
  "db/migrations/",
  "prisma/migrations/",
  "package-lock.json",
  "pnpm-lock.yaml",
  "yarn.lock",
];

const repo = process.env.GITHUB_REPOSITORY;
const event = JSON.parse(readFileSync(process.env.GITHUB_EVENT_PATH, "utf8"));
const run = event.workflow_run;
const gh = (args) => execFileSync("gh", args, { encoding: "utf8", maxBuffer: 16 * 1024 * 1024 });
const out = (key, value) => appendFileSync(process.env.GITHUB_OUTPUT, `${key}=${value}\n`);

function decide() {
  if (run?.conclusion !== "failure") return { action: "none", reason: "watched run did not fail" };
  const prNumber = run.pull_requests?.[0]?.number;
  if (!prNumber) return { action: "none", reason: "no same-repo PR attached to the failed run" };

  const pr = JSON.parse(gh(["api", `repos/${repo}/pulls/${prNumber}`]));
  if (pr.state !== "open" || pr.draft) return { action: "none", reason: "PR closed or draft" };

  const fingerprint = createHash("sha256")
    .update(`${run.name}|${run.head_branch}`)
    .digest("hex")
    .slice(0, 16);
  const marker = `<!-- facility-doctor:${fingerprint} -->`;
  const comments = JSON.parse(
    gh(["api", `repos/${repo}/issues/${prNumber}/comments?per_page=100`]),
  );
  if (comments.some((c) => c.body?.includes(marker))) {
    return { action: "none", reason: "this failure fingerprint was already handled on the PR" };
  }

  const failedJobs = JSON.parse(
    gh(["api", `repos/${repo}/actions/runs/${run.id}/jobs?per_page=50`]),
  )
    .jobs.filter((j) => j.conclusion === "failure")
    .map((j) => ({
      name: j.name,
      steps: (j.steps ?? []).filter((s) => s.conclusion === "failure").map((s) => s.name),
    }));

  const files = gh([
    "api",
    `repos/${repo}/pulls/${prNumber}/files?per_page=100`,
    "--jq",
    ".[].filename",
  ])
    .split("\n")
    .filter(Boolean);
  const sensitive = files.filter((f) =>
    SENSITIVE_PATHS.some((p) => f === p || f.startsWith(p) || f.includes(`/${p}`)),
  );
  const authorIsBot = (pr.user?.login ?? "").endsWith("[bot]");

  const base = { prNumber, pr, fingerprint, marker, failedJobs, sensitive };
  if (sensitive.length)
    return {
      ...base,
      action: "triage",
      reason: `PR touches sensitive surfaces (${sensitive.slice(0, 5).join(", ")})`,
    };
  if (!authorIsBot)
    return {
      ...base,
      action: "triage",
      reason: "human-authored PR — the doctor never commits to your branch uninvited",
    };
  return { ...base, action: "repair", reason: "crew-authored PR, non-sensitive failure" };
}

const decision = decide();
console.log(`doctor: ${decision.action} — ${decision.reason}`);
out("action", decision.action);
if (decision.action === "none") process.exit(0);

const jobsText = decision.failedJobs
  .map((j) => `- **${j.name}**${j.steps.length ? ` → ${j.steps.join(", ")}` : ""}`)
  .join("\n");

if (decision.action === "triage") {
  const body = [
    `**Doctor triage** — \`${run.name}\` failed on this PR ([run](${run.html_url})).`,
    "",
    jobsText,
    "",
    `Not auto-repaired: ${decision.reason}.`,
    decision.marker,
  ].join("\n");
  gh(["api", `repos/${repo}/issues/${decision.prNumber}/comments`, "-f", `body=${body}`]);
  process.exit(0);
}

// repair: hand the agent a sanitized task packet (names and refs only — no
// raw logs, which can carry secrets; the agent reproduces on the provisioned
// runner instead).
mkdirSync(".facility-doctor", { recursive: true });
writeFileSync(
  ".facility-doctor/context.json",
  JSON.stringify(
    {
      schema: "facility.doctor.context.v1",
      failure: { workflow: run.name, runUrl: run.html_url, failedJobs: decision.failedJobs },
      pr: {
        number: decision.prNumber,
        headRef: decision.pr.head.ref,
        baseRef: decision.pr.base.ref,
      },
      fingerprint: decision.fingerprint,
      marker: decision.marker,
    },
    null,
    2,
  ),
);
out("pr_number", String(decision.prNumber));
out("head_ref", decision.pr.head.ref);
out("fingerprint", decision.fingerprint);
