#!/usr/bin/env node
// Generated by facility — https://github.com/theam/facility
//
// PreToolUse hook (Edit|Write|MultiEdit). Protects files that must not be
// mutated casually (exit 2 = deny, stderr is shown to the agent).
//
// Real .env files hold live secrets — placeholders belong in .env.example.
// Facility modules may extend this file with extra protections (for example,
// the database module adds migration immutability).
import { readFileSync } from "node:fs";

function readPayload() {
  try {
    return JSON.parse(readFileSync(0, "utf8") || "{}");
  } catch {
    return {};
  }
}

const payload = readPayload();
// Claude Code on Windows sends tool_input.file_path with backslashes; the
// guards below are POSIX-style regexes, so normalise once, up front, for
// this file and every module fragment spliced in below.
const filePath = String(payload?.tool_input?.file_path ?? "").replace(/\\/g, "/");
if (!filePath) process.exit(0);

function block(reason) {
  console.error(`⛔ Blocked by .claude/hooks/protect-files.mjs\n${reason}`);
  process.exit(2);
}

if (/(^|\/)\.env(\.[\w.]+)?$/.test(filePath) && !/\.env\.example$/.test(filePath)) {
  block("Refusing to write a real .env file (secrets). Use .env.example for placeholders.");
}

/* facility:module-rules */

process.exit(0);
