#!/usr/bin/env node
// Generated by facility — https://github.com/theam/facility
//
// PreToolUse hook (Bash). Blocks a small set of unambiguously dangerous
// commands before they run (exit 2 = deny, stderr is shown to the agent).
// Deliberately narrow: it guards destructive/irreversible actions, not normal
// development.
import { readFileSync } from "node:fs";

const PROTECTED = /^(origin\/)?({{DEFAULT_BRANCH}}|main|master)$/;

function readPayload() {
  try {
    return JSON.parse(readFileSync(0, "utf8") || "{}");
  } catch {
    return {};
  }
}

const command = readPayload()?.tool_input?.command ?? "";
if (!command) process.exit(0);

const tokens = command.split(/\s+/);
const has = (t) => tokens.includes(t);
const targetsProtected = (t) => PROTECTED.test(t) || /:({{DEFAULT_BRANCH}}|main|master)$/.test(t);
const targetsProtectedRef = tokens.some(targetsProtected);
const isForce = has("--force") || has("-f") || has("--force-with-lease");

function block(reason) {
  console.error(`⛔ Blocked by .claude/hooks/protect-branch.mjs\n${reason}`);
  process.exit(2);
}

// Recursive force-remove rooted at filesystem root or $HOME.
if (
  /\brm\b/.test(command) &&
  /-[a-z]*r/i.test(command) &&
  /-[a-z]*f/i.test(command) &&
  /\s(\/|~|\$HOME)(\s|\/|$)/.test(command)
) {
  block("Recursive force-remove of a root or home path is not allowed.");
}

if (has("git") && has("push") && targetsProtectedRef && isForce) {
  block("Force-pushing the default branch is not allowed. Use a feature branch + PR.");
}

if (has("git") && has("push") && targetsProtectedRef) {
  block("Direct pushes to the default branch are not allowed — open a PR (see STANDARD.md).");
}

if (/>>?\s*\.?\/?\.env(\.[\w.]+)?\b/.test(command) && !/\.env\.example\b/.test(command)) {
  block(
    "Refusing to redirect output into a real .env file (secrets). Edit .env.example for placeholders.",
  );
}

process.exit(0);
